[global]
respect_gitignore = true
flavor            = "gfm"

[MD013]
line-length = 100   # Line length
code-blocks = false # Exclude code blocks from line length check
tables      = false # Exclude tables from line length check
headings    = true  # Include headings in line length check
reflow      = true  # Reflow text to fit line length
